server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai #GMT+8
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.31.250:3306/ka-mall?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  redis:
    host: 192.168.31.250
  #配置java mail
  mail:
    host: smtp.163.com
    username: kamisora2020@163.com
    password: VBWQMVCCRAHOFNDE
    port: 465
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true